name: deploymnet-workflow

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo Hello, ${{ inputs.username }}
      - name: Test
        run: |
          echo Hello, "$ORG"
          if [ "$ORG" == "ORG" ]
          then
            echo "aaa"
          fi
        env:
          ORG: ${{ secrets.ORG_TEST }}
        
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: build
    
    steps:
       - name: check user permission
         uses: 74th/workflow-permission-action@1.0.0
         with:
           users: vikramk20
       - uses: trstringer/manual-approval@v1
         with:
           secret: ${{ github.token }}
           approvers: vikramk20   
       - name: Deploy
         run: echo Hello, ${{ inputs.username }}
  
